In [1]:
import numpy as np
from IPython.display import display
import pandas as pd

In [24]:
df = pd.read_csv("C:/Users/Selin/Desktop/mobile (1).csv")

In [28]:
# question num 1
def last_one(name):
    return str(name)[0]

df['First name'] = df['Customer Name'].apply(last_one)
df

,Customer Name,Phone Number,Talked,Internet,Start Subscription,Cell phone company,First name
0,Cynthia Wong MD,050-5380527,231,944,14/09/2022,Pelephone,C
1,Chad Reed,053-5250617,166,217,28/11/2022,Motorola,C
2,James Murphy,051-7292166,483,437,06/04/2021,Golan,J
3,John Dean,054-2952436,435,817,06/01/2021,054,J
4,Nancy Bright,052-8402824,208,770,10/10/2022,Cellcom,N
5,Melinda Ruiz,051-3102790,434,903,23/02/2022,Golan,M
6,Kristin Huber,054-8068151,499,592,18/01/2023,054,K
7,Jesus Burke,052-8352627,48,467,19/10/2020,Cellcom,J
8,Joanna Buchanan,051-3167949,342,919,17/12/2023,Golan,J
9,Christian Lewis,052-3069795,277,740,11/04/2023,Cellcom,C
10,Amanda Meyer,050-8200916,355,390,03/02/2023,Pelephone,A
11,Aaron Melendez,050-8270179,553,871,29/01/2023,Pelephone,A
12,Sierra Morgan,054-6460585,590,614,17/04/2023,054,S
13,Timothy Frost,050-5915117,324,429,28/02/2020,Pelephone,T
14,Keith Lee,052-7653726,256,795,28/10/2022,Cellcom,K
15,Evelyn Elliott,051-6233404,369,705,17/10/2022,Golan,E
16,Chad Carter,053-9294578,25,350,06/10/2020,Motorola,C
17,Matthew Mills,052-7974129,670,571,08/07/2022,Cellcom,M
18,Jeffrey Hicks,050-8469039,250,99,07/05/2022,Pelephone,J
19,Janice Palmer,051-8678768,472,105,04/10/2021,Golan,J
20,Diana Scott,051-8932363,134,519,26/04/2021,Golan,D
21,Lacey Henry,051-7222641,58,104,20/06/2023,Golan,L
22,Angela Waters,054-5779698,553,201,19/10/2020,054,A
23,Lisa Alvarado,052-1692691,162,389,28/07/2021,Cellcom,L
24,Jessica Pittman,053-9160566,170,899,23/03/2023,Motorola,J
25,Ryan Aguirre,050-4964995,520,372,07/11/2023,Pelephone,R
26,Alison Moore,050-6467180,105,579,29/11/2020,Pelephone,A
27,Sarah Martin,051-6973566,24,91,12/04/2023,Golan,S
28,Gregory Stevens,052-7378700,30,858,09/08/2022,Cellcom,G
29,Jennifer Zavala,053-8258482,591,202,29/06/2020,Motorola,J
30,Ryan Aguirre,050-4964995,520,372,07/11/2023,Pelephone,R
31,John Dean,054-2952436,435,817,06/01/2021,054,J
32,Evelyn Elliott,051-6233404,369,705,17/10/2022,Golan,E
33,Alison Moore,050-6467180,105,579,29/11/2020,Pelephone,A
34,Jessica Pittman,053-9160566,170,899,23/03/2023,Motorola,J

In [29]:
# question num 2
prefix_to_company = {
    '050': 'Pelephone',
    '051': 'Golan',
    '052': 'Cellcom',
    '053': 'Motorola'
}

df['Cell phone company'] = df['Phone Number'].str[:3]

df['Cell phone company'] = df['Cell phone company'].replace(prefix_to_company)
df

,Customer Name,Phone Number,Talked,Internet,Start Subscription,Cell phone company,First name
0,Cynthia Wong MD,050-5380527,231,944,14/09/2022,Pelephone,C
1,Chad Reed,053-5250617,166,217,28/11/2022,Motorola,C
2,James Murphy,051-7292166,483,437,06/04/2021,Golan,J
3,John Dean,054-2952436,435,817,06/01/2021,054,J
4,Nancy Bright,052-8402824,208,770,10/10/2022,Cellcom,N
5,Melinda Ruiz,051-3102790,434,903,23/02/2022,Golan,M
6,Kristin Huber,054-8068151,499,592,18/01/2023,054,K
7,Jesus Burke,052-8352627,48,467,19/10/2020,Cellcom,J
8,Joanna Buchanan,051-3167949,342,919,17/12/2023,Golan,J
9,Christian Lewis,052-3069795,277,740,11/04/2023,Cellcom,C
10,Amanda Meyer,050-8200916,355,390,03/02/2023,Pelephone,A
11,Aaron Melendez,050-8270179,553,871,29/01/2023,Pelephone,A
12,Sierra Morgan,054-6460585,590,614,17/04/2023,054,S
13,Timothy Frost,050-5915117,324,429,28/02/2020,Pelephone,T
14,Keith Lee,052-7653726,256,795,28/10/2022,Cellcom,K
15,Evelyn Elliott,051-6233404,369,705,17/10/2022,Golan,E
16,Chad Carter,053-9294578,25,350,06/10/2020,Motorola,C
17,Matthew Mills,052-7974129,670,571,08/07/2022,Cellcom,M
18,Jeffrey Hicks,050-8469039,250,99,07/05/2022,Pelephone,J
19,Janice Palmer,051-8678768,472,105,04/10/2021,Golan,J
20,Diana Scott,051-8932363,134,519,26/04/2021,Golan,D
21,Lacey Henry,051-7222641,58,104,20/06/2023,Golan,L
22,Angela Waters,054-5779698,553,201,19/10/2020,054,A
23,Lisa Alvarado,052-1692691,162,389,28/07/2021,Cellcom,L
24,Jessica Pittman,053-9160566,170,899,23/03/2023,Motorola,J
25,Ryan Aguirre,050-4964995,520,372,07/11/2023,Pelephone,R
26,Alison Moore,050-6467180,105,579,29/11/2020,Pelephone,A
27,Sarah Martin,051-6973566,24,91,12/04/2023,Golan,S
28,Gregory Stevens,052-7378700,30,858,09/08/2022,Cellcom,G
29,Jennifer Zavala,053-8258482,591,202,29/06/2020,Motorola,J
30,Ryan Aguirre,050-4964995,520,372,07/11/2023,Pelephone,R
31,John Dean,054-2952436,435,817,06/01/2021,054,J
32,Evelyn Elliott,051-6233404,369,705,17/10/2022,Golan,E
33,Alison Moore,050-6467180,105,579,29/11/2020,Pelephone,A
34,Jessica Pittman,053-9160566,170,899,23/03/2023,Motorola,J

In [32]:
# question num 3 A
df['Cell phone company'].value_counts()

Cell phone company
Pelephone    9
Golan        9
Cellcom      7
Motorola     5
054          5
Name: count, dtype: int64

In [33]:
# question num 3 B
df['Cell phone company'].unique()

array(['Pelephone', 'Motorola', 'Golan', '054', 'Cellcom'], dtype=object)

In [34]:
# question num 3 C
df['Cell phone company'].nunique()

5

In [35]:
# question num 4 A
df['User Type'] = df.apply(lambda row: 'talker' if row['Talked'] > row['Internet'] else 'surfer',axis=1)
df

,Customer Name,Phone Number,Talked,Internet,Start Subscription,Cell phone company,First name,User Type
0,Cynthia Wong MD,050-5380527,231,944,14/09/2022,Pelephone,C,surfer
1,Chad Reed,053-5250617,166,217,28/11/2022,Motorola,C,surfer
2,James Murphy,051-7292166,483,437,06/04/2021,Golan,J,talker
3,John Dean,054-2952436,435,817,06/01/2021,054,J,surfer
4,Nancy Bright,052-8402824,208,770,10/10/2022,Cellcom,N,surfer
5,Melinda Ruiz,051-3102790,434,903,23/02/2022,Golan,M,surfer
6,Kristin Huber,054-8068151,499,592,18/01/2023,054,K,surfer
7,Jesus Burke,052-8352627,48,467,19/10/2020,Cellcom,J,surfer
8,Joanna Buchanan,051-3167949,342,919,17/12/2023,Golan,J,surfer
9,Christian Lewis,052-3069795,277,740,11/04/2023,Cellcom,C,surfer
10,Amanda Meyer,050-8200916,355,390,03/02/2023,Pelephone,A,surfer
11,Aaron Melendez,050-8270179,553,871,29/01/2023,Pelephone,A,surfer
12,Sierra Morgan,054-6460585,590,614,17/04/2023,054,S,surfer
13,Timothy Frost,050-5915117,324,429,28/02/2020,Pelephone,T,surfer
14,Keith Lee,052-7653726,256,795,28/10/2022,Cellcom,K,surfer
15,Evelyn Elliott,051-6233404,369,705,17/10/2022,Golan,E,surfer
16,Chad Carter,053-9294578,25,350,06/10/2020,Motorola,C,surfer
17,Matthew Mills,052-7974129,670,571,08/07/2022,Cellcom,M,talker
18,Jeffrey Hicks,050-8469039,250,99,07/05/2022,Pelephone,J,talker
19,Janice Palmer,051-8678768,472,105,04/10/2021,Golan,J,talker
20,Diana Scott,051-8932363,134,519,26/04/2021,Golan,D,surfer
21,Lacey Henry,051-7222641,58,104,20/06/2023,Golan,L,surfer
22,Angela Waters,054-5779698,553,201,19/10/2020,054,A,talker
23,Lisa Alvarado,052-1692691,162,389,28/07/2021,Cellcom,L,surfer
24,Jessica Pittman,053-9160566,170,899,23/03/2023,Motorola,J,surfer
25,Ryan Aguirre,050-4964995,520,372,07/11/2023,Pelephone,R,talker
26,Alison Moore,050-6467180,105,579,29/11/2020,Pelephone,A,surfer
27,Sarah Martin,051-6973566,24,91,12/04/2023,Golan,S,surfer
28,Gregory Stevens,052-7378700,30,858,09/08/2022,Cellcom,G,surfer
29,Jennifer Zavala,053-8258482,591,202,29/06/2020,Motorola,J,talker
30,Ryan Aguirre,050-4964995,520,372,07/11/2023,Pelephone,R,talker
31,John Dean,054-2952436,435,817,06/01/2021,054,J,surfer
32,Evelyn Elliott,051-6233404,369,705,17/10/2022,Golan,E,surfer
33,Alison Moore,050-6467180,105,579,29/11/2020,Pelephone,A,surfer
34,Jessica Pittman,053-9160566,170,899,23/03/2023,Motorola,J,surfer

In [42]:
# question num 4 B
def user_type(call, internet):
    return 'talker' if call > internet else 'surfer'

df['User Typ'] = np.vectorize(user_type)(df['Talked'], df['Internet'])

In [45]:
# question num 5 A
df_sorted_talk = df.sort_values('Talked', ascending=True)
df_sorted_talk

,Customer Name,Phone Number,Talked,Internet,Start Subscription,Cell phone company,First name,User Type,User Typ
27,Sarah Martin,051-6973566,24,91,12/04/2023,Golan,S,surfer,surfer
16,Chad Carter,053-9294578,25,350,06/10/2020,Motorola,C,surfer,surfer
28,Gregory Stevens,052-7378700,30,858,09/08/2022,Cellcom,G,surfer,surfer
7,Jesus Burke,052-8352627,48,467,19/10/2020,Cellcom,J,surfer,surfer
21,Lacey Henry,051-7222641,58,104,20/06/2023,Golan,L,surfer,surfer
26,Alison Moore,050-6467180,105,579,29/11/2020,Pelephone,A,surfer,surfer
33,Alison Moore,050-6467180,105,579,29/11/2020,Pelephone,A,surfer,surfer
20,Diana Scott,051-8932363,134,519,26/04/2021,Golan,D,surfer,surfer
23,Lisa Alvarado,052-1692691,162,389,28/07/2021,Cellcom,L,surfer,surfer
1,Chad Reed,053-5250617,166,217,28/11/2022,Motorola,C,surfer,surfer
34,Jessica Pittman,053-9160566,170,899,23/03/2023,Motorola,J,surfer,surfer
24,Jessica Pittman,053-9160566,170,899,23/03/2023,Motorola,J,surfer,surfer
4,Nancy Bright,052-8402824,208,770,10/10/2022,Cellcom,N,surfer,surfer
0,Cynthia Wong MD,050-5380527,231,944,14/09/2022,Pelephone,C,surfer,surfer
18,Jeffrey Hicks,050-8469039,250,99,07/05/2022,Pelephone,J,talker,talker
14,Keith Lee,052-7653726,256,795,28/10/2022,Cellcom,K,surfer,surfer
9,Christian Lewis,052-3069795,277,740,11/04/2023,Cellcom,C,surfer,surfer
13,Timothy Frost,050-5915117,324,429,28/02/2020,Pelephone,T,surfer,surfer
8,Joanna Buchanan,051-3167949,342,919,17/12/2023,Golan,J,surfer,surfer
10,Amanda Meyer,050-8200916,355,390,03/02/2023,Pelephone,A,surfer,surfer
15,Evelyn Elliott,051-6233404,369,705,17/10/2022,Golan,E,surfer,surfer
32,Evelyn Elliott,051-6233404,369,705,17/10/2022,Golan,E,surfer,surfer
5,Melinda Ruiz,051-3102790,434,903,23/02/2022,Golan,M,surfer,surfer
31,John Dean,054-2952436,435,817,06/01/2021,054,J,surfer,surfer
3,John Dean,054-2952436,435,817,06/01/2021,054,J,surfer,surfer
19,Janice Palmer,051-8678768,472,105,04/10/2021,Golan,J,talker,talker
2,James Murphy,051-7292166,483,437,06/04/2021,Golan,J,talker,talker
6,Kristin Huber,054-8068151,499,592,18/01/2023,054,K,surfer,surfer
30,Ryan Aguirre,050-4964995,520,372,07/11/2023,Pelephone,R,talker,talker
25,Ryan Aguirre,050-4964995,520,372,07/11/2023,Pelephone,R,talker,talker
22,Angela Waters,054-5779698,553,201,19/10/2020,054,A,talker,talker
11,Aaron Melendez,050-8270179,553,871,29/01/2023,Pelephone,A,surfer,surfer
12,Sierra Morgan,054-6460585,590,614,17/04/2023,054,S,surfer,surfer
29,Jennifer Zavala,053-8258482,591,202,29/06/2020,Motorola,J,talker,talker
17,Matthew Mills,052-7974129,670,571,08/07/2022,Cellcom,M,talker,talker

In [46]:
# question num 5 B
df['Total Time'] = df['Talked'] + df['Internet']
df_sorted_by_total = df.sort_values(by='Total Time', ascending=True)
df_sorted_by_total

,Customer Name,Phone Number,Talked,Internet,Start Subscription,Cell phone company,First name,User Type,User Typ,Total Time
27,Sarah Martin,051-6973566,24,91,12/04/2023,Golan,S,surfer,surfer,115
21,Lacey Henry,051-7222641,58,104,20/06/2023,Golan,L,surfer,surfer,162
18,Jeffrey Hicks,050-8469039,250,99,07/05/2022,Pelephone,J,talker,talker,349
16,Chad Carter,053-9294578,25,350,06/10/2020,Motorola,C,surfer,surfer,375
1,Chad Reed,053-5250617,166,217,28/11/2022,Motorola,C,surfer,surfer,383
7,Jesus Burke,052-8352627,48,467,19/10/2020,Cellcom,J,surfer,surfer,515
23,Lisa Alvarado,052-1692691,162,389,28/07/2021,Cellcom,L,surfer,surfer,551
19,Janice Palmer,051-8678768,472,105,04/10/2021,Golan,J,talker,talker,577
20,Diana Scott,051-8932363,134,519,26/04/2021,Golan,D,surfer,surfer,653
26,Alison Moore,050-6467180,105,579,29/11/2020,Pelephone,A,surfer,surfer,684
33,Alison Moore,050-6467180,105,579,29/11/2020,Pelephone,A,surfer,surfer,684
10,Amanda Meyer,050-8200916,355,390,03/02/2023,Pelephone,A,surfer,surfer,745
13,Timothy Frost,050-5915117,324,429,28/02/2020,Pelephone,T,surfer,surfer,753
22,Angela Waters,054-5779698,553,201,19/10/2020,054,A,talker,talker,754
29,Jennifer Zavala,053-8258482,591,202,29/06/2020,Motorola,J,talker,talker,793
28,Gregory Stevens,052-7378700,30,858,09/08/2022,Cellcom,G,surfer,surfer,888
25,Ryan Aguirre,050-4964995,520,372,07/11/2023,Pelephone,R,talker,talker,892
30,Ryan Aguirre,050-4964995,520,372,07/11/2023,Pelephone,R,talker,talker,892
2,James Murphy,051-7292166,483,437,06/04/2021,Golan,J,talker,talker,920
4,Nancy Bright,052-8402824,208,770,10/10/2022,Cellcom,N,surfer,surfer,978
9,Christian Lewis,052-3069795,277,740,11/04/2023,Cellcom,C,surfer,surfer,1017
14,Keith Lee,052-7653726,256,795,28/10/2022,Cellcom,K,surfer,surfer,1051
24,Jessica Pittman,053-9160566,170,899,23/03/2023,Motorola,J,surfer,surfer,1069
34,Jessica Pittman,053-9160566,170,899,23/03/2023,Motorola,J,surfer,surfer,1069
15,Evelyn Elliott,051-6233404,369,705,17/10/2022,Golan,E,surfer,surfer,1074
32,Evelyn Elliott,051-6233404,369,705,17/10/2022,Golan,E,surfer,surfer,1074
6,Kristin Huber,054-8068151,499,592,18/01/2023,054,K,surfer,surfer,1091
0,Cynthia Wong MD,050-5380527,231,944,14/09/2022,Pelephone,C,surfer,surfer,1175
12,Sierra Morgan,054-6460585,590,614,17/04/2023,054,S,surfer,surfer,1204
17,Matthew Mills,052-7974129,670,571,08/07/2022,Cellcom,M,talker,talker,1241
31,John Dean,054-2952436,435,817,06/01/2021,054,J,surfer,surfer,1252
3,John Dean,054-2952436,435,817,06/01/2021,054,J,surfer,surfer,1252
8,Joanna Buchanan,051-3167949,342,919,17/12/2023,Golan,J,surfer,surfer,1261
5,Melinda Ruiz,051-3102790,434,903,23/02/2022,Golan,M,surfer,surfer,1337
11,Aaron Melendez,050-8270179,553,871,29/01/2023,Pelephone,A,surfer,surfer,1424

In [50]:
# question num 6 A
top_5_talkers = df.nlargest(5, 'Talked')
top_5_talkers['Customer Name']

17      Matthew Mills
29    Jennifer Zavala
12      Sierra Morgan
11     Aaron Melendez
22      Angela Waters
Name: Customer Name, dtype: object

In [51]:
# question num 6 B
bottom_3_surfers = df.nsmallest(3, 'Internet')
bottom_3_surfers['Customer Name']

27     Sarah Martin
18    Jeffrey Hicks
21      Lacey Henry
Name: Customer Name, dtype: object

In [53]:
# question num 7 A
duplicates = df[df.duplicated()]

# question num 7 B
df_no_duplicates = df.drop_duplicates()
df_no_duplicates

,Customer Name,Phone Number,Talked,Internet,Start Subscription,Cell phone company,First name,User Type,User Typ,Total Time
0,Cynthia Wong MD,050-5380527,231,944,14/09/2022,Pelephone,C,surfer,surfer,1175
1,Chad Reed,053-5250617,166,217,28/11/2022,Motorola,C,surfer,surfer,383
2,James Murphy,051-7292166,483,437,06/04/2021,Golan,J,talker,talker,920
3,John Dean,054-2952436,435,817,06/01/2021,054,J,surfer,surfer,1252
4,Nancy Bright,052-8402824,208,770,10/10/2022,Cellcom,N,surfer,surfer,978
5,Melinda Ruiz,051-3102790,434,903,23/02/2022,Golan,M,surfer,surfer,1337
6,Kristin Huber,054-8068151,499,592,18/01/2023,054,K,surfer,surfer,1091
7,Jesus Burke,052-8352627,48,467,19/10/2020,Cellcom,J,surfer,surfer,515
8,Joanna Buchanan,051-3167949,342,919,17/12/2023,Golan,J,surfer,surfer,1261
9,Christian Lewis,052-3069795,277,740,11/04/2023,Cellcom,C,surfer,surfer,1017
10,Amanda Meyer,050-8200916,355,390,03/02/2023,Pelephone,A,surfer,surfer,745
11,Aaron Melendez,050-8270179,553,871,29/01/2023,Pelephone,A,surfer,surfer,1424
12,Sierra Morgan,054-6460585,590,614,17/04/2023,054,S,surfer,surfer,1204
13,Timothy Frost,050-5915117,324,429,28/02/2020,Pelephone,T,surfer,surfer,753
14,Keith Lee,052-7653726,256,795,28/10/2022,Cellcom,K,surfer,surfer,1051
15,Evelyn Elliott,051-6233404,369,705,17/10/2022,Golan,E,surfer,surfer,1074
16,Chad Carter,053-9294578,25,350,06/10/2020,Motorola,C,surfer,surfer,375
17,Matthew Mills,052-7974129,670,571,08/07/2022,Cellcom,M,talker,talker,1241
18,Jeffrey Hicks,050-8469039,250,99,07/05/2022,Pelephone,J,talker,talker,349
19,Janice Palmer,051-8678768,472,105,04/10/2021,Golan,J,talker,talker,577
20,Diana Scott,051-8932363,134,519,26/04/2021,Golan,D,surfer,surfer,653
21,Lacey Henry,051-7222641,58,104,20/06/2023,Golan,L,surfer,surfer,162
22,Angela Waters,054-5779698,553,201,19/10/2020,054,A,talker,talker,754
23,Lisa Alvarado,052-1692691,162,389,28/07/2021,Cellcom,L,surfer,surfer,551
24,Jessica Pittman,053-9160566,170,899,23/03/2023,Motorola,J,surfer,surfer,1069
25,Ryan Aguirre,050-4964995,520,372,07/11/2023,Pelephone,R,talker,talker,892
26,Alison Moore,050-6467180,105,579,29/11/2020,Pelephone,A,surfer,surfer,684
27,Sarah Martin,051-6973566,24,91,12/04/2023,Golan,S,surfer,surfer,115
28,Gregory Stevens,052-7378700,30,858,09/08/2022,Cellcom,G,surfer,surfer,888
29,Jennifer Zavala,053-8258482,591,202,29/06/2020,Motorola,J,talker,talker,793

In [55]:
df.sample()

,Customer Name,Phone Number,Talked,Internet,Start Subscription,Cell phone company,First name,User Type,User Typ,Total Time
0,Cynthia Wong MD,050-5380527,231,944,14/09/2022,Pelephone,C,surfer,surfer,1175

In [57]:
winners = df.sample(n=3) 
winners[['Customer Name', 'Phone Number']]

      Customer Name Phone Number
8   Joanna Buchanan  051-3167949
2      James Murphy  051-7292166
33     Alison Moore  050-6467180